import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Input, Heading, Editable,EditableInput, EditablePreview, Link, Text, Box, Alert, AlertIcon, AlertTitle, CloseButton, Button, useColorMode } from "@chakra-ui/react";
import '@kfonts/nanum-gothic';
import '@fortawesome/fontawesome-free';
import { useState } from "react";
import moment from "moment";
import CustomTimer from "../components/CustomTimer"
import Konami from 'react-konami-code';
import fx from 'fireworks';

const Timer: NextPage = () => {
  const [setting, setSetting] = useState(false);
  const [date, setDate] = useState(new Date());
  const [error, setError] = useState(false);
  const [errormessage, setEM] = useState("");
  let Toggle = () => {
    setSetting(!setting);
  }
  let range = (n: number) => [...new Array(n)]
  
    function doFireworks(n: number){
      range(n).map(() =>
        fx({
          x: Math.random() * (window.innerWidth / 2) + window.innerWidth / 4,
          y: Math.random() * window.innerHeight / 2,
          colors: ['#AEC6CF', '#fdfd96', '#81C784', '#F57BA9'],
          bubbleSizeMinimum: 10
        })
      )
  }
  const { colorMode, toggleColorMode } = useColorMode()
  let easterEgg = () => {
    for(let i = 0;i<10;i++){
      setInterval(() => doFireworks(1), Math.random()*2500*i);
      // toggleColorMode();
    }
    toggleColorMode();
    setTimeout(()=>alert(1), 1000);
    toggleColorMode();
    // setInterval(() => toggleColorMode(), 1000)
  }

  return (
    <div className={styles.container} style={{backgroundImage: `url("strawberry.png")`, textShadow: `-1px 0 black, 0 1px black, 1px 0 black, 0 -1px black`}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Heading className={styles.title} as="h1" size="4xl" mb="2">
          <Editable defaultValue="Strawberry Moon">
            <EditablePreview />
            <EditableInput />
          </Editable>
        </Heading>
        <p className={styles.description}>
        </p>
        <br />
        {!error ? null :
                <>
                  <Alert style={{borderRadius: "lg"}} status="error">
                    <AlertIcon />
                    <AlertTitle mr={2}>{errormessage}</AlertTitle>
                  </Alert>
                </>
        }
        
        <Box className={styles.timerBoxstraw} overflow="hidden" style={{ fontWeight: 300 }}>
          <CustomTimer onClick={Toggle} expiryTimestamp={new Date("2021-10-19T00:00:00")} style={{ fontWeight: 400 }} />
        </Box>
      </main>

      <footer className={styles.footer}>
        <Link className="ftlink" onClick={() => setDate(moment(new Date()).add(1, 'days').toDate())} target="_blank" hr="https://school.gyo6.net/gbsw">
          <span className={styles.gbsw}><Image src="/symbol-only.png" alt="GBSW Logo" width="50%" height="50%" /></span>
          Gyeongbuk Software HighSchool
        </Link>
        <Text style={{marginRight: '7vw'}}>made by ღ redesigned, jademon</Text>
        <Konami action={easterEgg} />
      </footer>
    </div>
  );
};

export default Timer;
